using CliWrap;

namespace Devantler.CLIRunner.Tests.CLITests;

/// <summary>
/// Integration tests for the <see cref="CLI.RunAsync"/> method.
/// </summary>
public class RunAsyncTests
{
  /// <summary>
  /// Tests that the <see cref="CLI.RunAsync"/> method returns the expected exit code and stdout result
  /// </summary>
  /// <returns></returns>
  // Generated by Copilot
  [Fact]
  public async Task RunAsync_GivenValidCommand_ReturnsZeroExitCodeAndStdout()
  {
    // Arrange
    var command = new Command("echo").WithArguments("Hello, World!");
    var cancellationToken = CancellationToken.None;
    var validation = CommandResultValidation.ZeroExitCode;
    bool silent = false;

    // Act
    var (exitCode, result) = await CLI.RunAsync(command, validation, silent, cancellationToken: cancellationToken);

    // Assert
    Assert.Equal(0, exitCode);
    Assert.Contains("Hello, World!", result, StringComparison.Ordinal);
  }

  /// <summary>
  /// Tests that the <see cref="CLI.RunAsync"/> method returns the expected exit code and stderr result
  /// </summary>
  /// <returns></returns>
  [Fact]
  public async Task RunAsync_GivenInvalidCommand_ReturnsOneExitCodeAndNoOutput()
  {
    // Arrange
    var command = new Command("ech")
      .WithArguments("Hello, World!");
    var cancellationToken = CancellationToken.None;
    var validation = CommandResultValidation.ZeroExitCode;
    bool silent = false;

    // Act
    var (exitCode, _) = await CLI.RunAsync(command, validation, silent, cancellationToken: cancellationToken);

    // Assert
    Assert.Equal(1, exitCode);
  }

  /// <summary>
  /// Tests that the <see cref="CLI.RunAsync"/> method returns the expected exit code and stderr result
  /// </summary>
  /// <returns></returns>
  [Fact]
  public async Task RunAsync_GivenInvalidArgument_ReturnsOneExitCodeAndStderr()
  {
    // Arrange
    var command = new Command("cat")
      .WithArguments("--invalid")
      .WithValidation(CommandResultValidation.ZeroExitCode);
    var cancellationToken = CancellationToken.None;
    bool silent = false;

    // Act
    var (exitCode, _) = await CLI.RunAsync(command, CommandResultValidation.ZeroExitCode, silent, cancellationToken: cancellationToken);

    // Assert
    Assert.Equal(1, exitCode);
  }
}


